-- 创建聊天消息表
CREATE TABLE T_CHAT_MESSAGE (
    MSG_ID_C VARCHAR(36) PRIMARY KEY,
    MSG_SENDER_ID_C VARCHAR(36) NOT NULL,
    MSG_RECEIVER_ID_C VARCHAR(36) NOT NULL,
    MSG_CONTENT_C TEXT NOT NULL,
    MSG_CREATEDATE_D TIMESTAMP NOT NULL,
    MSG_READ_B BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (MSG_SENDER_ID_C) REFERENCES T_USER(USE_ID_C),
    FOREIGN KEY (MSG_RECEIVER_ID_C) REFERENCES T_USER(USE_ID_C)
);

-- 创建索引以提高查询性能
CREATE INDEX IDX_CHAT_MSG_SENDER ON T_CHAT_MESSAGE(MSG_SENDER_ID_C);
CREATE INDEX IDX_CHAT_MSG_RECEIVER ON T_CHAT_MESSAGE(MSG_RECEIVER_ID_C);
CREATE INDEX IDX_CHAT_MSG_DATE ON T_CHAT_MESSAGE(MSG_CREATEDATE_D); 