-- 创建聊天消息表
CREATE TABLE T_CHAT_MESSAGE (
    MSG_ID_C VARCHAR(36) PRIMARY KEY,
    MSG_SENDER_USERNAME_C VARCHAR(50) NOT NULL,
    MSG_RECEIVER_USERNAME_C VARCHAR(50) NOT NULL,
    MSG_CONTENT_C TEXT NOT NULL,
    MSG_CREATEDATE_D TIMESTAMP NOT NULL,
    MSG_READ_B BOOLEAN NOT NULL DEFAULT FALSE
);

-- 创建索引以提高查询性能
CREATE INDEX IDX_CHAT_MSG_SENDER ON T_CHAT_MESSAGE(MSG_SENDER_USERNAME_C);
CREATE INDEX IDX_CHAT_MSG_RECEIVER ON T_CHAT_MESSAGE(MSG_RECEIVER_USERNAME_C);
CREATE INDEX IDX_CHAT_MSG_DATE ON T_CHAT_MESSAGE(MSG_CREATEDATE_D); 